### ISSUE TITLE
Demo page not working

### ISSUE THREAD

**Issue by dmartinho** [myforce/angularjs-dropdown-multiselect#1]
It's me or the demo page is not working ? 
http://myforce.github.io/angularjs-dropdown-multiselect/

Console log
Failed to load resource: the server responded with a status of 404 (Not Found)

https://rawgit.com/pc035860/angular-highlightjs/master/angular-highlightjs.js Failed to load resource: the server responded with a status of 500 (Internal Server Error)

angular.js:3809 Uncaught Error: [$injector:modulerr] Failed to instantiate module exampleApp due to:
Error: [$injector:modulerr] Failed to instantiate module hljs due to:
Error: [$injector:nomod] Module 'hljs' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.

**Comment by pkempenaers** [comment]
Yeah indeed, seems like rawgit is having some issues. I'll look into removing rawgit

**Comment by pkempenaers** [comment]
I've removed the rawgit url and from my end the demo page is working

**Comment by dmartinho** [comment]
Well done sir ! Thank you !
