### ISSUE TITLE
event.srcElement non-standard

### ISSUE THREAD

**Issue by neemanjabu** [myforce/angularjs-dropdown-multiselect#11]
Functions `keyDownLink` and `keyDownSearchDefault` relies on `event.srcElement` property which is non-standard and causes JS errors. `event.target ` should be used here.

https://developer.mozilla.org/en-US/docs/Web/API/Event/srcElement

**Comment by neemanjabu** [comment]
Problem is that jQuery does not copy `srcElement` property from `originalEvent` to jQuery `Event` object. Quick fix would be to add `srcElement` to jQuery `Event` object using fixHooks.

```
$.event.fixHooks.keydown = {
	props: [ "srcElement" ]
};
```

**Comment by pkempenaers** [comment]
Thanks for notifying me, I'll take a look at this, this afternoon

**Comment by Shouvikg** [comment]
thanks neemanjabu. you saved my day. that change in source code haled a lot

**Comment by pkempenaers** [comment]
Hi,

Once again thank you for bringing this to my attention, this has been resolved in versions:
1.7.3, 1.8.2 and 1.9.1 (and higher)
