### ISSUE TITLE
Checkboxes is not checked by default

### ISSUE THREAD

**Issue by tienvx** [myforce/angularjs-dropdown-multiselect#14]
```
<div ng-dropdown-multiselect="" options="columns" selected-model="visibleColumns" extra-settings="{
    scrollableHeight: '500px',
    scrollable: true,
    displayProp: 'title',
    idProp: 'key',
    showCheckAll: false,
    showUncheckAll: false
}" checkboxes="true"></div>
```
```
var fields = {'first_name': {label: 'First Name', visible: true}, 'last_name': {label: 'Last Name', visible: true}};
vm.columns = [];
vm.visibleColumns = [];
angular.forEach(fields, function (field, key) {
  vm.columns.push({ key: key, title: field.title });
  if (field.visible) {
    vm.visibleColumns.push({key: key});
  }
});
```
I think because of the custom display prop and id prop. Because when I change the code to:
```
 vm.columns.push({ id: key, label: field.title });
if (field.visible) {
  vm.visibleColumns.push({id: key});
}
```
and remove:
```
displayProp: 'title',
idProp: 'key',
```
from the extra settings, it'll work.
These settings I use from the original project [dotansimha/angularjs-dropdown-multiselect](https://github.com/dotansimha/angularjs-dropdown-multiselect). Not sure your project still supports them.

**Comment by pkempenaers** [comment]
First issue in your example is that you field.title is undefined so
`vm.columns.push({ id: key, label: field.title });`
should be
` vm.columns.push({ id: key, label: field.label });`

The other issue is that you push {key: ...} objects to selectedModel while it expects {id: ...} objects. You can however set externalIdProp to 'key' which will let selectedModel expect {key: ...} objects.
