### ISSUE TITLE
Is there any option to select the dropdown list using tab key in keyboard ???

### ISSUE THREAD

**Issue by vaksanth** [myforce/angularjs-dropdown-multiselect#36]
Hi ,

Need to know , how to open the multi-select drop down using tab key instead of space bar and enter key.

Advance thanks for ur help :)

**Comment by pkempenaers** [comment]
You'll have to do that yourself in a separate fork, I've opted to use the same behavior as with a normal html select element. Which gets focused with tab and is controlled with arrows, space bar and enter.
