### ISSUE TITLE
package not found with bower install

### ISSUE THREAD

**Issue by BrokenHip** [myforce/angularjs-dropdown-multiselect#37]
When i put  "myforce-angularjs-dropdown-multiselect": "1.10.2" in bower.json and do bower install, bower doesn't find the package.

bower myforce-angularjs-dropdown-multiselect#1.10.2        ENOTFOUND Package myforce-angularjs-dropdown-multiselect not found

**Comment by pkempenaers** [comment]
I can't seem to reproduce this, can you give me the exact logging?

**Comment by BrokenHip** [comment]
I can't really give more.

$ bower install myforce-angularjs-dropdown-multiselect
bower bootstrap#3.3.7           cached git://private-bower.schaubroeck.be:6789/bootstrap#3.3.7
bower bootstrap#3.3.7         validate 3.3.7 against git://private-bower.schaubroeck.be:6789/bootstrap#3.3.7
bower myforce-angularjs-dropdown-multiselect#1.10.2        ENOTFOUND Package myforce-angularjs-dropdown-multiselect not found

**Comment by pkempenaers** [comment]
Are you able to install other bower packages that are hosted on github?

**Comment by BrokenHip** [comment]
I am currently updating our dependencies. I also installed a new package last week from github so yes that shouldn't be the problem

**Comment by pkempenaers** [comment]
Could you try
`bower install 'git://github.com/myforce/angularjs-dropdown-multiselect.git'`

**Comment by BrokenHip** [comment]
strange I got it working by adding the link to github instead of the version in bower.json:

    "myforce-angularjs-dropdown-multiselect": "https://github.com/myforce/angularjs-dropdown-multiselect"

now it downloaded. No idea why it doesn't work normally

**Comment by pkempenaers** [comment]
Probably something to do with bower checking only your private git server
