### ISSUE TITLE
Add watch to value of selected-model ?

### ISSUE THREAD

**Issue by atentis** [myforce/angularjs-dropdown-multiselect#43]
Hello, 

I would like to put a watch on the value of the selected-model in your example. For some reason the watch never fires when I change the selection in the multiselect. Is it possible to do this?  Thanks
```
   <div ng-dropdown-multiselect="" options="example1data" selected-model="example1model"> </div> 

   $scope.example1model = {}; 
   $scope.example1data = [{ id: 1, label: "David" }, { id: 2, label: "Jhon" }, { id: 3, label: "Danny" }];

   $scope.$watch("example1model", function (newValue, oldValue) {
         console.log(newValue);
   }); 
```

**Comment by pkempenaers** [comment]
We have events for that. Also selected-model should be an array. If you still have some problems, create a Plunkr and I'll see if I can help

**Comment by atentis** [comment]
@pkempenaers Yeah my bad on the selected-model. I created a plunker for you and am seeing that even with using idProp I am only getting the selected Ids. Is there a way to get the selected lables (text values)?

Thanks for your help.

https://plnkr.co/edit/n2ZDcKWbKALyQeAYPnR6?p=preview

**Comment by pkempenaers** [comment]
Setting externalIdProp to "label" will only return object with only the labels, setting it to "" will return the full objects.

I've forked your plnkr with the first solution:
https://plnkr.co/edit/a3phKxQ7iO5dtyS2Bybd?p=preview

**Comment by atentis** [comment]
Thank you for your help. Another control was a better fit but I may return to this one when I have a list with ids. Please close this issue.
