### ISSUE TITLE
Inherit width of container

### ISSUE THREAD

**Issue by gavinbelson** [myforce/angularjs-dropdown-multiselect#46]
Great module. I can't seem to make the select button inherit the width of the containing bootstrap <div>. I tried the stylesheets but no luck. Where could I adjust the width to be 100% of a container?

**Comment by MissingLinke** [comment]
Adding these two lines to my style sheet helped.

**Comment by gavinbelson** [comment]
That's super helpful. Thank you!!

Can be used to adjust width to px as well: { width: 100px; }

**Comment by pkempenaers** [comment]
Just an fyi this repo is no longer maintained here, I've been maintaining the main repo https://github.com/dotansimha/angularjs-dropdown-multiselect

**Comment by MissingLinke** [comment]
Thank you.  I did find that one and posted a few issues I'm having in there as well.
