### ISSUE TITLE
Multiple directives [ngDropdownMultiselect, ngDropdownMultiselect] asking for new/isolated scope on

### ISSUE THREAD

**Issue by shreeshagundmi** [myforce/angularjs-dropdown-multiselect#47]
Hi There,
I am using  AngularJS v1.4.6
when i use angularjs-dropdown-multiselect i'm getting bellow error

Error: [$compile:multidir] Multiple directives [ngDropdownMultiselect, ngDropdownMultiselect] asking for new/isolated scope on: <div ng-dropdown-multiselect="" options="example1data" selected-model="example1model">

can anyone help me ..?
![error](https://cloud.githubusercontent.com/assets/24886410/23361522/2038c4e0-fd17-11e6-9e2c-8dce119317ed.PNG)

**Comment by pkempenaers** [comment]
are you using this fork together with the main fork? because you can go back to the main fork
