### ISSUE TITLE
Keyboard Controls not Working

### ISSUE THREAD

**Issue by CronGM** [myforce/angularjs-dropdown-multiselect#6]
Hello. The keyboard controls are not working in the demo anymore. I remember choosing to work with your fork over the original one because of this. Any idea why this is happening?

**Comment by pkempenaers** [comment]
I've fixed this. The problem was that I used event listeners instead of ng-keydown. When the "lazy loading" of the list was introduced adding event listeners on opening didn't work any more.

This fix should be included in 1.2.6, 1.3.8, 1.4.1 and higher
