### ISSUE TITLE
Custom Options

### ISSUE THREAD

**Issue by sirago** [myforce/angularjs-dropdown-multiselect#7]
Is there a way to add my own options (along with Check All and Uncheck All)?

I'm using these as filters and having a button to remove the textbox -- i.e. remove filter -- would be awesome.

Thanks!

**Comment by pkempenaers** [comment]
I think having custom options could be rather hard. But adding the 'enable filter' - 'disable filter' is something that can be done if that's all you need. I'll start working on it.

**Comment by pkempenaers** [comment]
I've implemented this. And it's included in version 1.5.0 and up.

**Comment by sirago** [comment]
Awesome, thank you!
