### ISSUE TITLE
Style warning when using content security policy (CSP)

### ISSUE THREAD

**Issue by TomJahncke** [myforce/angularjs-dropdown-multiselect#9]
Thank you for branching this libraries and continuing to keep it current.  

My application is using content security policy (CSP).  With CSP I have it setup to prevent inline CSS styles.  This library in-lines two styles.  (line 33: style="overflow: auto", line 39: style="width: 100%;")  

The warning that is produced in the console log (Chrome) is:
{code}
angular.min.js:190 Refused to apply inline style because it violates the following Content Security Policy directive: "style-src 'self'". Either the 'unsafe-inline' keyword, a hash ('sha256-N6tSydZ64AHCaOWfwKbUhxXx2fRFDxHOaL3e3CO7GPI='), or a nonce ('nonce-...') is required to enable inline execution.
{code}

I will attach a simple application that demonstrates this issue.

**Comment by TomJahncke** [comment]
[multi-select-csp-issue.zip](https://github.com/myforce/angularjs-dropdown-multiselect/files/268154/multi-select-csp-issue.zip)

**Comment by pkempenaers** [comment]
Hi,

I've fixed this. The fix is included in versions:
1.8.1, 1.7.2, 1.6.1, 1.5.1, 1.4.2, 1.3.10, 1.2.8, 1.1.6 (and up)

**Comment by TomJahncke** [comment]
Thank you so much for the fix and an amazing fast turnaround.  I am now using version 1.8.1 and my issue has been addressed.
